### PR TITLE
Add password_hash support to auth.php

### PR DESCRIPTION
**Pull request by max-weller**
With the current implementation of auth.php, it is not possible to use proper password hashing because you need the `pw` from the database to check the salted hash.

This pull request implements a new option `[ 'pwhash' => true ]`. If this is set, passwords are not compared directly but the recommended [`password_verify`](http://php.net/password_verify) function of php is used.

### CODE REVIEW

**Comment by max-weller** [comment]
Unit Test: https://gist.github.com/max-weller/b52db38824d29f9937b2

**Comment by max-weller** [comment]
Unit Test Results:
```
% rm -f _test.sqlite; php f3_auth_password_hash_test.php
Using test db: /home/maxweller/Projekte/f3-core/_test.sqlite
Test user created successfully                          Pass
Correct login was accepted                              Pass
Wrong username was rejected                             Pass
Wrong password was rejected                             Pass
```

**Comment by ikkez** [comment]
It would probably be better to add a way for a custom password comparison check instead of adding just **one** option. *password_verify* is not the only option someone could need. So instead of add a limited check pw function, reuse the `$args` array from the construct and add a custom anonymous function here that's been used to checking passwords, maybe like:

```php
$auth = new Auth($sqlMapper,array('custom' => function($user,$hash) {
  return \Bcrypt::instance()->verify($user->pw,$hash);
}));
```

As this could be difficult with the current implementation, another way is to remove the Jig, Mongo, and SQL auth types completely, and only use the auth plugin for 3rd party authentication services (LDAP, OAuth, OpenConnect, etc.). Using this for your own SQL datasets with an unknown password mechanism might cause just trouble and it was a pretty often discussed and misunderstood topic in the community

**Comment by max-weller** [comment]
Hi,
I just updated my branch so it can be merged again. I'd really like it if f3 would finally support encrypted passwords, not making users of the framework [Plaintext Offenders](http://plaintextoffenders.com/about/) by default. 
The password_hash/password_verify methods are the officially recommended methods to do this, so I think a customizable password check is not that important. 

Kind regards,
Max

**Comment by ikkez** [comment]
You can add a custom compare method now:

```php
$success = $auth->login($id,$password,NULL,function($pw,$hash) {
	return password_verify($pw,$hash);
});
```

**Comment by KOTRET** [comment]
As creating the $auth-Instance is bound to one mapper at a time, the function should be passed into the constructor instead into the login-method.

**Comment by ikkez** [comment]
alright, I've changed it now.

**Comment by damjes** [comment]
Please also update documentation, because current doesn't say a thing about possibility of using i.e. password_verify.

**Pull request closed without merging**
