### PR TITLE
New: ttl attribute in <include>

### PR DESCRIPTION
**Pull request by xfra35**
Usage:
```html
<include href="somefile.html" ttl="86400"/>
```

### CODE REVIEW

**Comment by ikkez** [comment]
:+1:

**Comment by KOTRET** [comment]
:+1:

**Comment by Rayne** [comment]
The PR doesn't work for me as it doesn't clear the cached result after `5` seconds. Am I using it wrong?

[Source with generated files](https://gist.github.com/Rayne/031112f6300c0970f96b)

I also noticed that `Cache` and `Preview` are handling `$ttl` with a significant difference:

**Cache->set()**

> If $ttl is 0 then the entry is saved for an infinite time. Otherwise, the specified time, in seconds, is used as TTL.

**Preview->render()** (which doesn't use the `$ttl` argument of `Cache`)

> if ($ttl) $cache->set($hash,$data);

**Comment by KOTRET** [comment]
yes, the call to Cache at [base.php#2683](https://github.com/bcosca/fatfree-core/blob/master/base.php#L2683) must be
```php
$cache->set($hash,$data, $ttl);
```

**Comment by xfra35** [comment]
Well spotted guys!

**Pull request merged**
