### PR TITLE
Fix PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by jtojnar**
Cleaned up #332 and added some more fixes

### CODE REVIEW

**Comment by ikkez** [comment]
I'll have a look at this soon.

**Comment by jtojnar** [comment]
Any luck @ikkez?

**Comment by ikkez** [comment]
almost done.

**Comment by ikkez** [comment]
should be good to go now. I've build a new dev bench for all unit tests and testings across multiple php version https://github.com/f3-factory/fatfree-dev

I'll tag a new release soon.

**Comment by maietta** [comment]
Been waiting a while on this one! Thank you all so much!

**Pull request merged**
