### PR TITLE
Image: allow absolute paths

### PR DESCRIPTION
**Pull request by xfra35**
The Image constructor doesn't make any distinction between absolute and relative paths.

This PR intends to fix that. Additionally it raises an error if the file can't be found.

### CODE REVIEW

**Comment by adaniello** [comment]
Thanks!

**Comment by ikkez** [comment]
hm, can't we use the `$path` constructor argument for setting an absolute path already?

**Comment by xfra35** [comment]
I thought about it too, changing:
```php
$fw->split($path?:$fw->get('UI').';./')
```
into
```php
$fw->split(isset($path)?$path:$fw->get('UI').';./')
```
But the `split()` method removes any *empty* element, which includes `''`.

Or did you mean splitting the filename in two? Like `new Image(basename($path),FALSE,dirname($path))` instead of `new Image($path)`? That would probably work, although a bit less user-friendly :P

**Comment by ikkez** [comment]
Well, basically i thought about splitting the filename in two, yes. probably not that comfortable, but that's how i do it atm. I was not aware of the split function, that it removes the empty elements. Soo, i guess improving this thing is reasonable.

**Comment by xfra35** [comment]
I made an alternative PR, which allows `$path=''`. I think this way, we're closer to the initial logic.

**Pull request closed without merging**
